CHUNK_SIZE    = 800
CHUNK_OVERLAP = 120
MIN_CHUNK_LEN = 120
BATCH_SIZE    = 32

EMBEDDING_MODEL = "BAAI/bge-m3"
EMBEDDING_DIM   = 1024

RERANKER_MODEL  = "BAAI/bge-reranker-v2-m3"
TOP_K_RETRIEVAL = 30
TOP_K_FINAL     = 3

LLM_MODEL       = "llama3.2"
MAX_HISTORY     = 3
MAX_HISTORY_MEM = 20
